# Generated by Django 4.1 on 2022-08-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_teamleader',
            field=models.BooleanField(default=False, verbose_name='team-leader status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_teammember',
            field=models.BooleanField(default=False, verbose_name='team-member status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_user',
            field=models.BooleanField(default=False, verbose_name='user status'),
        ),
    ]
